### ISSUE TITLE
Loadouts on Respawn?

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/CO_Template.Stratis#6]

**Comment by Fusselwurm** [comment]
Should work, buuut I haven't tested it

**Comment by McDiod** [comment]
Funktionierte gestern nicht, aber hier ist der Fix:
https://github.com/gruppe-adler/grad-loadout/pull/5

Bitte Template updaten, sobald gemerged :)

**Comment by McDiod** [comment]
updated
